# Generated by Django 3.2.9 on 2021-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reposts',
            field=models.IntegerField(default=0),
        ),
    ]
