# Generated by Django 3.2.9 on 2021-12-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingem', '0003_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
